### ISSUE TITLE
COMPS XML files

### ISSUE THREAD

**Issue by MTwinchek** [usgpo/uslm#32]
When pulling the data from the COMPS section of statutes there is an issue with the appropriations measures where the following coding are not being compiled rather are appearing as continued text.

- <compsdtd:subsubaccount commented="no" _id="OF COURSE THIS VARYS"_ in-effect="yes" type="subsequent"><compsdtd:header bold="off" display-inline="yes-display-inline">

- <compsdtd:appropriations-para (Item 1)
Additionally, where there are tables within the compilation the tables are unformed and show up as small continuous text. (Item 4)
Finally, there are coding issues where >.</content> shows up in the code, and when translated shows up on a separate line where it should be inline with the prior text. (Item 3)

Comps utilized for this example: COMPS-1422; COMPS-16716 

![Item 4](https://github.com/usgpo/uslm/assets/148595180/bbe9bfbb-05a7-4b7b-9700-89d142351843)
![Item 3](https://github.com/usgpo/uslm/assets/148595180/d3c42d08-4539-4144-a76b-0e493f21c80a)
![Item 1](https://github.com/usgpo/uslm/assets/148595180/93e12d31-9b01-4010-adda-5a8adb2b72b2)
16716

**Comment by bradleechang** [comment]
@MTwinchek

The process that creates the USLM versions of COMPS includes a conversion from an older format named "compsdtd".  This process currently has limitations.  Content that is not yet supported in USLM is passed though in a <foreign> element that include the original <compdtd> tagging.  This preserves the content, but the rendering in the browser will not be styled.  This behavior is what you are seeing with <compsdtd:subsubaccount>, <compsdtd:appropriations-para> and <compsdtd:table>.

The issue with the period appearing on a separate line is a limitation of the CSS renderingtechnology.  The data is semantically correct in that the period is outside of the quoted content. 

We are happy to answer further questions.
