### ISSUE TITLE
USLM 2.1 for only bill text or also bill status?

### ISSUE THREAD

**Issue by sibiliab** [usgpo/uslm#37]
Hi,

I was reviewing the sample USLM 2.1 xml files available in [this repo](https://github.com/usgpo/uslm/tree/proposed/bill-version-samples-september-2024). It looks like all the sample files are for bill text. Will there be updates to the bill status xml files as well, or does USLM 2.1 only apply to the bill text? If there will be revisions to the bill status xml files, can you please point me to where I can find them? Thanks!

**Comment by llaplant** [comment]
USLM 2.1 is only for bill text, not bill status. There are no planned changes to bill status related to USLM.

**Comment by sibiliab** [comment]
Thanks @llaplant! Is there an expected time at which USLM 2.1 xml files will be deployed to production on the bulk data site? And will historical bills/bills from previous congresses also be converted to USLM 2.1?
