### ISSUE TITLE
Correct meaning of term URL

### ISSUE THREAD

**Issue by ericamick** [usgpo/uslm#4]
URL actually stands for Uniform Resource Locator.

**Comment by jonquandt** [comment]
Hi, @ericamick -- I see it  -- https://github.com/usgpo/uslm/blob/master/USLM-User-Guide.md#121-concept.

We'll get that updated in an upcoming release

**Comment by llaplant** [comment]
Corrected in https://github.com/usgpo/uslm/blob/proposed/USLM-User-Guide.md#121-concept
