### ISSUE TITLE
USLM-User-Guide markdown fixes

### ISSUE THREAD

**Issue by aleksandarbos** [usgpo/uslm#6]
Looks like markdown is not formatted properly for the table in section 4.4:
![image](https://user-images.githubusercontent.com/15141614/45693211-e0efd700-bb5c-11e8-8efb-4bb6c1ed92fc.png)
I took some time to fix it, but later I saw that i should report an issue instead of creating the PR directly.

Also on section 3. Inhertiance, markdown for `` `<level role="chapter">`_ _is roughly analogous to `<chapter> ``
you missed the `` ` `` after `<chapter>`. 
![image](https://user-images.githubusercontent.com/15141614/45693600-c407d380-bb5d-11e8-9bb3-8b53bd1d2baa.png)

**Comment by llaplant** [comment]
Fixed formatting in remaining tables https://github.com/usgpo/uslm/blob/proposed/USLM-User-Guide.md
